### ISSUE TITLE
DOC: Short section on methedology

### ISSUE THREAD

**Issue by mroeschke** [dogpackdesign/apn-formats#7]
First, I want to say thanks for this great resource. 

I am interested to learn more about how these formats and regexs were developed. Do the formats compass (potential) previous APN formats used by a county? Are these formats valid as of the present day (March 2018)?

Clarifying these points would be really helpful in the README.rst would be really awesome. 

Thanks.

**Comment by proulx712** [comment]
Hey Matthew! Glad we could provide a package that's useful! The formats we've collected we're back in 2016 and haven't been updated since then. Definitely an interesting feature to add would be to provide date ranges encompassing previous APN formats. We've been involved in other projects but we'll update once we get to updating the package!

**Comment by mroeschke** [comment]
Hi Eric. Thanks for the context! If you have the time for one more follow up question, was there a resource that directly gave you the APN formats or did you develop a tool to extract a format given an APN?
